#############################注意不要用使用TAB键进行对齐排版之类的##############################
#服务
server:
    port: 9031 #启动端口
#网关
spring:
    application:
        name: ${spring.cloud.config.name:api-gate}
    loadbalancer:
      retry:
        enabled: false
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    http:
        encoding:
          force: true
          charset: UTF-8
          enabled: true
#启用Feign 客户端Hystrix 熔断
feign.hystrix.enabled: true
#ribbon配置
ribbon:
  eureka:
      enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: true
  ConnectTimeout: 20000
  ReadTimeout: 20000
  httpclient: #禁用默认的httpclient
      enabled: false
  okhttp: #启用okhttp
      enabled: true
#防雪崩利器：熔断器
hystrix:
  threadpool:
    default:
      coreSize: 200 ##并发执行的最大线程数，默认10
      maxQueueSize: 200 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 50 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000 #20秒超时
            ribbon:
                ReadTimeout: 20000
                ConnectTimeout: 20000
#请求和响应GZIP压缩支持
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
endpoints:
  shutdown:
    #启用shutdown
    enabled: true
    #禁用密码验证
    sensitive: false
    #禁用路径
    path: XxILZtZjrY0VucfOYlsiCLr3zRsHWO2C
#管理端口
management:
    port: 281
    address: 127.0.0.1