#spring配置
spring:
    datasource:
        name: db_easework
        url: jdbc:mysql://172.16.1.15:3306/db_easework?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
        username: easework
        password: 6ZXv2Mzn5?E4
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall,slf4j #统计、防火墙、日志
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validation_query: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:  
        database: 1
        host: 172.16.1.17
        port: 6382
        password: 33RhWlr9cG
        pool:  
          max-active: 64  
          max-idle: 8  
          min-idle: 0  
          max-wait: 10000
    rabbitmq:
        host: 172.16.4.16
        port: 5672
        username: ibu
        password: ibu123
#服务名称映射(与相关服务client中的feign服务名对应) 用到了哪些client, 就配置上相关的, 没用到可以不用配置
platform-service: 
    service-id: 
        auth: auth-bs #认证服务
user:
    password: 123456
#认证服务客户端
auth: 
    service-id: auth-bs #认证服务
    client: 
        id: user-bs
        secret: 123456
        token-header: client-token
        service-auth: false #是否启用服务间认证
        user-auth: false #启用用户认证
        rest-log: false #启用REST请求日志记录
    user: 
        token-header: access-token